<?php

#
# Do not edit this file!
# Use SYSCONFDIR/pinger-config.php instead.
#

/**
 * Конфигурация сервиса Pinger. Значения по умолчанию
 * 
 * @package Pinger
 * @subpackage Service
 * 
 * @author      Sergey D. Ivanov <me@dev.ganzal.com>
 * @copyright   Copyright (c) 2016, Sergey D. Ivanov
 * 
 * @version 0.1.0
 * @see Config
 */
return [
    /**
     * Пользователь-владелец Мастер-процесса.
     * 
     * @var string
     */
    'exec_user' => 'nobody',
    /**
     * Группа-владелец Мастер-процесса.
     * 
     * @var string
     */
    'exec_group' => 'nogroup',
    /**
     * Лимит дочерних процессов Воркеров.
     * 
     * 0 - отключает лимит, Мастер ориентируется на
     *  кол-во хостов в списке <code>hosts:enabled</code> лимитируя
     *  себя 32 одновременными потоками.
     * 
     * @var int
     */
    'fork_threads' => 0,
    /**
     * Сервер разрешения доменных имён.
     * 
     * @var string
     */
    'nslookup_server' => '',
    /**
     * Хост СУБД MySQL.
     * 
     * @var string|null
     */
    'mysql_host' => 'localhost',
    /**
     * Порт СУБД MySQL.
     * 
     * @var int
     */
    'mysql_port' => 3306,
    /**
     * Сокет СУБД MySQL.
     * 
     * @var string
     */
    'mysql_sock' => '/var/run/mysqld/mysqld.sock',
    /**
     * Кодировка соединения с СУБД MySQL.
     * 
     * @var string
     */
    'mysql_cset' => 'utf8',
    /**
     * Пользователь СУБД MySQL.
     * 
     * @var string
     */
    'mysql_user' => 'root',
    /**
     * Пароль пользователя СУБД MySQL.
     * 
     * @var string
     */
    'mysql_pass' => '',
    /**
     * Имя базы сервиса Pinger в СУБД MySQL.
     * 
     * @var string
     */
    'mysql_base' => 'pinger',
    /**
     * Таймаут пинга хоста в очереди <code>queue:ping:ok</code>.
     * 
     * @var int
     */
    'ping_timeout_ok' => 1,
    /**
     * Таймаут пинга хоста в очереди <code>queue:ping:prefailed</code>.
     * 
     * @var int
     */
    'ping_timeout_prefail' => 5,
    /**
     * Таймаут пинга хоста в очереди <code>queue:ping:failed</code>.
     * 
     * @var int
     */
    'ping_timeout_fail' => 1,
    /**
     * Шаблон команды <code>ping</code>.
     * 
     * @var string
     */
    'ping_command' => '/usr/bin/env ping -c1 -W%1$d -n -q %2$s',
    /**
     * Хост сервера Redis.
     * 
     * @var string
     */
    'redis_host' => '127.0.0.1',
    /**
     * Порт сервера Redis.
     * 
     * @var int
     */
    'redis_port' => 6379,
    /**
     * Таймаут ожидания подключения к серверу Redis.
     * 
     * @var float
     */
    'redis_wait' => 1.0,
    /**
     * Перфикс ключей в кэше Redis.
     * 
     * @var string
     */
    'redis_bank' => 'pinger',
];

# EOF